name: gen_rpc_toc
on:
  push:
    branches: [ master ]
    paths:
      - '**.md'
jobs:
  generateTOC:
    name: gen_rpc_toc
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
